# Generated by Django 2.1.7 on 2020-07-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('TENANT', 'Tenant'), ('EMPLOYEE', 'Employee')], default='OWNER', max_length=10),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
