# Generated by Django 2.1.7 on 2019-03-30 22:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20190331_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqId', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(default='running', max_length=30)),
            ],
            options={
                'db_table': 'cctv',
            },
        ),
        migrations.RemoveField(
            model_name='building',
            name='elevators',
        ),
        migrations.AddField(
            model_name='elevator',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Building'),
        ),
        migrations.AddField(
            model_name='cctv',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Building'),
        ),
    ]
