# Generated by Django 2.1.7 on 2019-03-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20190331_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='elevators_id',
            field=models.IntegerField(null=True),
        ),
    ]
