# Generated by Django 2.1.7 on 2019-03-30 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_building_elevators_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='elevators_id',
        ),
    ]
